name: Stok Takip Botu

on:
  schedule:
    - cron: '*/15 * * * *'  # Her 15 dakikada bir çalışır
  workflow_dispatch:        # Elle çalıştırma butonu

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Depoyu Çek
        uses: actions/checkout@v3

      - name: Python Kurulumu
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Kütüphaneleri Yükle
        run: pip install -r requirements.txt
          
      - name: Botu Çalıştır
        run: python main.py
          
      - name: Botu Çalıştır
        run: python main.py
